### ISSUE TITLE
Hello World example in README throws a TypeError

### ISSUE THREAD

**Issue by kenbellows** [eno-lang/enojs#1]
Currently the example in `README.md` contains these two lines:

    const input = fs.readFileSync('intro.eno');
    
    const document = eno.parse(input);

When run, the following type error is thrown:

    /data/code/eno-test/node_modules/enojs/eno.js:29
        throw new TypeError(
        ^
    
    TypeError: The parser accepts only strings as input, input was: Greeting: Hello World!

This is because the call to `fs.readFileSync()` was not given an encoding, so `input` is a `Buffer` instead of a `String`. There's an easy fix:

    const input = fs.readFileSync('intro.eno', 'utf-8');

Written this way, everything runs as expected.

**Comment by kenbellows** [comment]
Put in a PR with the encoding fix.

**Comment by simonrepp** [comment]
Well spotted, I keep on accidentally omitting the `'utf-8'` although I've already hit the wall with it about 100 times, only here I didn't notice of course. :)

**Comment by kenbellows** [comment]
Same here! Without fail I write it without the encoding first, run my code, hit a `TypeError` somewhere, get confused, spend 10 minutes debugging it, spot it, slap my forehead, then fix it. It seems to be a universal constant.
