### ISSUE TITLE
How can I convert JSON to ENO ?

### ISSUE THREAD

**Issue by xet7** [eno-lang/enojs#3]
Hi,
How can I convert JSON to ENO ?

**Comment by simonrepp** [comment]
Hi! :wave: 

eno has no fixed types, this allows it to be very simple for users, but comes at the cost of losing generic de/serializability. (the rationale behind this: better that 1 developer needs to do more work and afterwards 10s/100s/1000s/... ;) of users have a really smooth ride and hardly any learning curve!)

In practice this currently means we need to convert by hand.

As for future perspective to make this easier I quote a Q&A I gave earlier on HN:
> Q: There is eno.parse(), but is there some kind of reverse mechanism to create a new Eno document? Like document.addList([...]).addSection('hey', 2) or something.
> 
> A: I want one! Obviously there can't be a stable generic "just dump it already" implementation, but a smart builder-type API is definitely on the list, I even started one for enojs but had to re-prioritize because there was so much else to do for the whole ecosystem. ;)

Thanks for giving eno a try, appreciate it! Absolutely feel free to open more issues if there's anything unclear!
